services:
  - type: web
    name: nhentai-play
    runtime: python
    pythonVersion: "3.10"
    buildCommand: |
        pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
